# Generated by Django 5.2.4 on 2025-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalalapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteeprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiteeprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='recruiteeprofile',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
