# Generated by Django 5.2.4 on 2025-07-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalalapi', '0002_recruiteeprofile_address_recruiteeprofile_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteeprofile',
            name='needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
