# Generated by Django 5.2.4 on 2025-07-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalalapi', '0003_recruiteeprofile_needs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiteeprofile',
            name='needs',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
