# Generated by Django 5.2.4 on 2025-07-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalalapi', '0004_remove_recruiteeprofile_needs_recruiterprofile_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiteeprofile',
            name='cv',
            field=models.FileField(default=None, upload_to='cvs/'),
            preserve_default=False,
        ),
    ]
